name: Daily npm Update

on:
  schedule:
    - cron: "0 20 * * *" # Run every day at 20:00 UTC
  workflow_dispatch: # Allow manual triggering

jobs:
  npm-update:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v4 # Latest stable version

      - name: Install npm-check-updates
        run: npm install -g npm-check-updates

      - name: Run npm-check-updates
        run: |
          ncu -u # Update dependencies in package.json
          npm install # Install updated dependencies
          npm audit fix # Auto-fix vulnerabilities

      - name: Commit updated dependencies
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add package.json package-lock.json
          git commit -m "Daily npm update" || echo "No changes to commit"

      - name: Push changes
        uses: ad-m/github-push-action@master # Latest available version
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Trigger Deployment Workflow
        uses: peter-evans/repository-dispatch@v2 # Latest stable version
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          event-type: npm-update-complete # Custom event name
